global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'

scrape_configs:
  -  job_name: 'prometheus'
     static_configs:
       -  targets: ['prometheus_monitoring:9090']
  -  job_name: 'node-exporter'
     static_configs:
       -  targets: ['node_exporter_monitoring:9100']
  -  job_name: 'docker-monitoring'
     static_configs:
       -  targets: ['cadvisor_monitoring:8080']

