version: "3.7"
services: 
  prometheus:
    image: prom/prometheus:v2.31.1
    restart: unless-stopped
    container_name: prometheus_monitoring
    user: "0"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      -  '--config.file=/etc/prometheus/prometheus.yml'
      -  '--storage.tsdb.retention.time=7d'
    ports:
      -  9090:9090
    depends_on: 
      -  cadvisor
      -  node-exporter
    networks:
      -  docker-monitoring
  node-exporter:
    image: prom/node-exporter:v1.3.0
    container_name: node_exporter_monitoring
    restart: unless-stopped
    ports:
      -  9100:9100
    networks:
      -  docker-monitoring
  
  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: cadvisor_monitoring
    restart: unless-stopped
    volumes: 
      -  /:/rootfs:ro
      -  /var/run:/var/run:rw
      -  /sys:/sys:ro
      -  /var/lib/docker/:/var/lib/docker:ro
    ports:
      -  8080:8080
    networks:
      -  docker-monitoring
  
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana_monitoring
    user: "0"
    restart: unless-stopped
    depends_on:
      -  prometheus
    volumes: 
      -  ./grafana/data:/var/lib/grafana
    environment: 
      -  GF_SECURITY_ADMIN_PASSWORD=AdmInPaSsW0rd
      -  GF_USER_ALLOW_SIGN_UP=false
    ports:
      -  3000:3000
    networks:
      -  docker-monitoring
  
networks:
  docker-monitoring:
